function System(os){
	if(os == 1){
		document.getElementById("install-os-detailed").innerHTML = " ";
		document.getElementById("install-os-detailed").innerHTML = "<h3>Windows</h3><h4>Creating an Install Drive</h4>You'll need a USB flash drive with at least 2 GB of free space and a program called Rufus.<br><div align='center'><br><a href='http://rufus.ie' target='_blank'><button><i class='fab fa-usb' style='color:white;'></i>&nbsp;&nbsp;Download Rufus</button></a></div><table><tr><td><img src='../img/installation/windows-rufus.png' alt='Rufus screenshot'></td><td><ol><li>Open Rufus</li><li>Insert your USB drive and select it in the \"Device\" list</li><li>Select \"Disk or ISO image\" in the \"Boot selection\" list</li><li>Click \"SELECT\" to choose the ISO that you downloaded previously.</li><li>We generate a checksum (or hash sum) for MiOS images so you can verify your downloaded file. This ensures that you've received the full, complete download and that your install image is not corrupted in any way. Click the checksum icon next to \"SELECT\" and verify that the text next to \"SHA256\" matches the following hash:<br><p class='highlight'>a8c7b8c54aeb0889bb3245356ffcd95b77e9835ffb5ac56376a3b627c3e1950f</p></li><li>If the hashes match, click \"START\" and wait for the process to finish.</li></ol></td></tr></table><h4>Booting from your installation drive</h4> In order to start the installation, you must boot computer from your USB drive. <ol><li>Assuming that your computer is still on, start by inserting your install drive and restarting your computer.</li><li>Most computers will briefly allow you to change the boot order for this boot only by pressing special key - usually <kbd>F12</kbd>, but sometimes <kbd>Esc</kbd> or another key. If you're not sure, check what's written on your screen or in documentation.</li><li>Press <kbd>F12</kbd> (or the appropriate key) and select the install drive - usually \"USB-HDD\" or something containing the word \"USB\", but wording may vary. If you choose the incorrect drive, your computer might boot into your normal OS. Just restart and select different drive in boot menu.</li><li>Shortly after selecting the appropriate boot drive, you should be presented with the MiOS splash screen. You may now follow the on-screen instructions which will guide you through the rest of the process</li></ol>";
	}
	else if(os == 2){
		document.getElementById("install-os-detailed").innerHTML = " ";
		document.getElementById("install-os-detailed").innerHTML = "<h3>macOS</h3><h4>Verifying your download</h4>Verifying your download is an important, but optional step. We generate a checksum (or hash sum) for MiOS images and we recommend that you verify that your download matches that checksum before trying to install. This ensures that you've received the full, complete download and that your install image is not corrupted in any way. <br>Run the following command in your Terminal:<p class='highlight'>shasum -a 256 ~Downloads/mios-alpha-0.1.iso</p>It should give you this result: <p class='highlight'>a8c7b8c54aeb0889bb3245356ffcd95b77e9835ffb5ac56376a3b627c3e1950f</p> Note: If you have downloaded .iso file to another directory you need to specify the path to the file, as show below: <p class='highlight'>shasum -a 256 &lt;path to downloaded folder&gt;/mios-alpha-0.1.iso</p><br><h4>Creating an Install Drive</h4> To create a MiOS install drive on macOS you'll need a USB flash drive with at least 2GB of space and an app called \"Etcher\".<br><div align='center'><br><a href='http://balena.io/etcher' target='_blank'><button><i class='fab fa-usb' style='color:white;'></i>&nbsp;&nbsp;Download Etcher</button></a><br><br><img src='../img/installation/etcher.gif'></div><ol><li>Insert the spare USB drive.</li><li>Open \"Etcher\" and select your downloaded MiOS image file using the \"Select image\" button.</li><li>Etcher should automatically detect your USB drive, but check to see if it has selected the correct target.</li><li>Start the flashing process by clicking the \"Flash!\" button. It will take a moment to get started.</li><li> When complete it will be safe to remove the drive and attempt to boot to install MiOS.</li></ol>The following dialog may appear during the flashing process, it is safe to ignore.<div align='center'><img src='../img/installation/macos-warning.png'></div><h4>Booting from the Install Drive</h4>In order to start the installation process you must boot your computer from the install drive. <ol><li>Assuming that your computer is still on, start by inserting your install drive and restarting your computer.</li><li>After you hear the chime, press and hold <kbd>Options</kbd>. Then, select the appropriate boot drive. Note that it may be incorrectly identified as \"Windows\", but this is normal.</li><li>Shortly after selecting the appropriate boot drive, you should be presented with the MiOS splash screen. You may now follow the on-screen instructions which will guide you through the rest of the process.</li></ol> <i>Boot errors</i><br><br>If your Mac doesn't recognize your MiOS USB Install Drive in the boot menu, you may need to create a MiOS Install DVD instead. To create one, insert a blank DVD, right click on the ISO file in Finder, and select \"Burn mios-alpha-0.1 to Disc\". When complete, attempt to boot again from the Install DVD.";
	}
	else if(os == 3){
		document.getElementById("install-os-detailed").innerHTML = " ";
		document.getElementById("install-os-detailed").innerHTML = "<h3>Linux</h3><h4>Verify your Download</h4>Verifying your download is an important, but optional step. We generate a checksum (or hash sum) for MiOS images and we recommend that you verify that your download matches that checksum before trying to install. This ensures that you've received the full, complete download and that your install image is not corrupted in any way.<br>Running the following command in your Terminal: <p class='highlight'>sha256sum mios-alpha-0.1.iso</p>should result with this output:<p class='highlight'>a8c7b8c54aeb0889bb3245356ffcd95b77e9835ffb5ac56376a3b627c3e1950f</p><h4>Creating an Install Drive</h4>You'll need a USB flash drive with at least 2 GB of free space and a program called UNetbootin.<br><div align='center'><br><a href='https://unetbootin.github.io/' target='_blank'><button><i class='fab fa-usb' style='color:white;'></i>&nbsp;&nbsp;Download Unetbootin</button></a></div> <ol><li>Open UNetbootin from the Dash. It wil open a windows like the one below:<br><img src='../img/installation/linux-unetbootin.png' align='center'></li><li>Select \"Diskimage\"</li><li>Click\"...\" to select the previously downloaded ISO</li><li>Unplug all USB memory devices apart from the one you want to use</li><li>Click \"OK\" and wait for the process to finish</li></ol><h4>Booting from the Install Drive</h4>In order to start the installation process, you must boot your PC from the install drive.<ul><li>Assuming that your computer is still on, start by inserting your install drive and restarting your computer.</li><li>Most computers will briefly allow you to change the boot order for this by pressing a special key - usually <kbd>F12</kbd>, but sometimes <kbd>Esc</kbd> or another function key. Refer to the screen or your computer's documentation to be sure.</li><li>Press <kbd>F12</kbd> or another appropriate keyand select the install drive - usually \"USB-HDD\" or something containing word \"USB\", bot the wording may vary. If you choose the incorrect option, your computer will likely boot as usual. You'll need to restart it ad pick another drive in boot menu.</li><li>Shortly after selecting the appropriate drive, you'll see the MiOS splash screen. From there, you have to follow on-screen instructions which will guide you through the rest of the process.</li></ul>";
	}
	else{
		document.getElementById("install-os-detailed").innerHTML = " ";
		document.getElementById("install-os-detailed").innerHTML = "Oh, so you're messing with \"Inspect element\" option? No way here, bro!";
	}
}